/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Dialog;

import javax.swing.JOptionPane;
import model.Pegawai;
import service.PegawaiService;

/**
 *
 * @author ryo not rio
 */
public class DialogPegawai extends javax.swing.JDialog {
    
    private boolean isUpdate = false;
private Pegawai dataPegawai;


    /**
     * Creates new form DialogPegawai
     */
  public DialogPegawai(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    loadComboJabatan();
}

    private void loadComboJabatan() {
    cmbJabatan.removeAllItems();
    cmbJabatan.addItem("Admin");
    cmbJabatan.addItem("Kasir");
}

    
    public void setInsertMode() {
    isUpdate = false;

    txtIDPegawai.setText("AUTO");
    txtIDPegawai.setEditable(false);

    txtNamaPegawai.setText("");
    txtUsername.setText("");
    jPassword.setText("");

    cmbJabatan.setSelectedIndex(0);

    btnSavePegawai.setText("SAVE");
}


public void setUpdateMode(Pegawai p) {
    isUpdate = true;
    this.dataPegawai = p;

    txtIDPegawai.setText(p.getId());
    txtIDPegawai.setEditable(false);

    txtNamaPegawai.setText(p.getNama());
    txtNamaPegawai.setEditable(true);

    txtUsername.setText(p.getUsername());
    txtUsername.setEditable(true);

    jPassword.setText(p.getPassword());   // ← FIX

    cmbJabatan.removeAllItems();
    cmbJabatan.addItem("Admin");
    cmbJabatan.addItem("Kasir");
    cmbJabatan.setSelectedItem(p.getJabatan());
    cmbJabatan.setEnabled(true);

    btnSavePegawai.setText("UPDATE");
}



     

     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jJudul2 = new javax.swing.JLabel();
        txtIDPegawai = new javax.swing.JTextField();
        btnSavePegawai = new javax.swing.JButton();
        btnCancelPegawai = new javax.swing.JButton();
        lblIDKategori = new javax.swing.JLabel();
        lblNamaKategori = new javax.swing.JLabel();
        jJudul1 = new javax.swing.JLabel();
        txtNamaPegawai = new javax.swing.JTextField();
        cmbJabatan = new javax.swing.JComboBox<>();
        txtUsername = new javax.swing.JTextField();
        lblNamaKategori1 = new javax.swing.JLabel();
        jJudul3 = new javax.swing.JLabel();
        jJudul4 = new javax.swing.JLabel();
        lblNamaKategori2 = new javax.swing.JLabel();
        jJudul5 = new javax.swing.JLabel();
        lblNamaKategori3 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("PEGAWAI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 28, -1, -1));

        jJudul2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul2.setText(":");
        getContentPane().add(jJudul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 117, -1, 28));

        txtIDPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDPegawaiActionPerformed(evt);
            }
        });
        getContentPane().add(txtIDPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 117, 350, 39));

        btnSavePegawai.setBackground(new java.awt.Color(0, 0, 102));
        btnSavePegawai.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSavePegawai.setForeground(new java.awt.Color(204, 255, 255));
        btnSavePegawai.setText("SAVE");
        btnSavePegawai.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));
        btnSavePegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePegawaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnSavePegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 393, 98, 36));

        btnCancelPegawai.setBackground(new java.awt.Color(153, 0, 0));
        btnCancelPegawai.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancelPegawai.setForeground(new java.awt.Color(204, 255, 255));
        btnCancelPegawai.setText("CANCEL");
        btnCancelPegawai.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 51, 51)));
        btnCancelPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelPegawaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 393, 98, 36));

        lblIDKategori.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori.setText("ID Pegawai");
        getContentPane().add(lblIDKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 120, 117, -1));

        lblNamaKategori.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamaKategori.setText("Nama Pegawai");
        getContentPane().add(lblNamaKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 168, -1, 28));

        jJudul1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul1.setText(":");
        getContentPane().add(jJudul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 168, -1, 28));

        txtNamaPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPegawaiActionPerformed(evt);
            }
        });
        getContentPane().add(txtNamaPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 168, 350, 38));

        cmbJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJabatanActionPerformed(evt);
            }
        });
        getContentPane().add(cmbJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 218, 350, 40));

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 350, 38));

        lblNamaKategori1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamaKategori1.setText("Jabatan");
        getContentPane().add(lblNamaKategori1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 218, -1, 28));

        jJudul3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul3.setText(":");
        getContentPane().add(jJudul3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 218, 18, 28));

        jJudul4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul4.setText(":");
        getContentPane().add(jJudul4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 272, 18, 28));

        lblNamaKategori2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamaKategori2.setText("Username");
        getContentPane().add(lblNamaKategori2, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 270, -1, 28));

        jJudul5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul5.setText(":");
        getContentPane().add(jJudul5, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 323, 23, 28));

        lblNamaKategori3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamaKategori3.setText("Password");
        getContentPane().add(lblNamaKategori3, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 322, -1, 28));
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 322, 350, 36));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DialogBG.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSavePegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePegawaiActionPerformed
  String nama = txtNamaPegawai.getText().trim();
    String jabatan = cmbJabatan.getSelectedItem().toString().trim();
    String username = txtUsername.getText().trim();
    String password = new String(jPassword.getPassword()).trim();

    PegawaiService service = new PegawaiService();

    // VALIDASI DASAR
    if (nama.isEmpty() || jabatan.isEmpty() || username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua field wajib diisi!");
        return;
    }

    // VALIDASI USERNAME DUPLIKAT (HANYA SAAT INSERT)
    if (!isUpdate) {
        if (service.existsByUsername(username)) {
            JOptionPane.showMessageDialog(this, 
                    "Username sudah digunakan! Gunakan username lain.");
            return; // FORM TETAP STAY
        }
    }

    boolean success = false;

    try {
        if (!isUpdate) {
            // INSERT MODE
            dataPegawai = new Pegawai();
            dataPegawai.setNama(nama);
            dataPegawai.setUsername(username);
            dataPegawai.setPassword(password);
            dataPegawai.setJabatan(jabatan);

        } else {
            // UPDATE MODE
            dataPegawai.setNama(nama);
            dataPegawai.setUsername(username);
            dataPegawai.setPassword(password);
            dataPegawai.setJabatan(jabatan);
        }

        success = true;

    } catch (Exception e) {
        JOptionPane.showMessageDialog(
            this,
            "Terjadi kesalahan saat menyimpan data pegawai: " + e.getMessage()
        );
    }

    // FORM TUTUP HANYA KALAU SUKSES
    if (success) {
        dispose();
    }
       // TODO add your handling code here:
    }//GEN-LAST:event_btnSavePegawaiActionPerformed

    private void btnCancelPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelPegawaiActionPerformed
        dataPegawai = null;
    dispose();
    }//GEN-LAST:event_btnCancelPegawaiActionPerformed

    private void txtNamaPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPegawaiActionPerformed

    private void cmbJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbJabatanActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtIDPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDPegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDPegawaiActionPerformed

    /**
     * @param args the command line arguments
     */
  
    
        public Pegawai getPegawai() {
    return dataPegawai;
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelPegawai;
    private javax.swing.JButton btnSavePegawai;
    private javax.swing.JComboBox<String> cmbJabatan;
    private javax.swing.JLabel jJudul1;
    private javax.swing.JLabel jJudul2;
    private javax.swing.JLabel jJudul3;
    private javax.swing.JLabel jJudul4;
    private javax.swing.JLabel jJudul5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JLabel lblIDKategori;
    private javax.swing.JLabel lblNamaKategori;
    private javax.swing.JLabel lblNamaKategori1;
    private javax.swing.JLabel lblNamaKategori2;
    private javax.swing.JLabel lblNamaKategori3;
    private javax.swing.JTextField txtIDPegawai;
    private javax.swing.JTextField txtNamaPegawai;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    
}
