/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Dialog;

import javax.swing.JOptionPane;
import model.Pembeli;
import service.PembeliService;

/**
 *
 * @author ryo not rio
 */
public class DialogPembeli extends javax.swing.JDialog {
private boolean isUpdate = false;
private Pembeli dataPembeli;

    /**
     * Creates new form DialogPembeli
     */
    public DialogPembeli(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
  public void setInsertMode(String idBaru) {
    isUpdate = false;

    txtIDPembeli.setEditable(false);
    txtIDPembeli.setText(idBaru);

    txtNamaPembeli.setText("");
    txtTeleponPembeli.setText("");
    txtAlamatPembeli.setText("");

    btnSavePembeli.setText("SAVE");
}



 public void setUpdateMode(Pembeli p) {
    isUpdate = true;
    this.dataPembeli = p;

    txtIDPembeli.setText(p.getIdPembeli());
    txtIDPembeli.setEditable(false);

    txtNamaPembeli.setText(p.getNamaPembeli());
    txtTeleponPembeli.setText(p.getNoTelepon());
    txtAlamatPembeli.setText(p.getAlamat());

    btnSavePembeli.setText("UPDATE");
}


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jJudul2 = new javax.swing.JLabel();
        txtIDPembeli = new javax.swing.JTextField();
        btnSavePembeli = new javax.swing.JButton();
        btnCancelPembeli = new javax.swing.JButton();
        lblIDKategori = new javax.swing.JLabel();
        lblNamaKategori = new javax.swing.JLabel();
        txtTeleponPembeli = new javax.swing.JTextField();
        jJudul1 = new javax.swing.JLabel();
        jJudul3 = new javax.swing.JLabel();
        lblIDKategori1 = new javax.swing.JLabel();
        lblNamaKategori1 = new javax.swing.JLabel();
        jJudul5 = new javax.swing.JLabel();
        jJudul4 = new javax.swing.JLabel();
        txtNamaPembeli = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamatPembeli = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("PEMBELI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 36, -1, -1));

        jJudul2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul2.setText(":");
        getContentPane().add(jJudul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 132, -1, 28));

        txtIDPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDPembeliActionPerformed(evt);
            }
        });
        getContentPane().add(txtIDPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 130, 350, 39));

        btnSavePembeli.setBackground(new java.awt.Color(0, 0, 102));
        btnSavePembeli.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSavePembeli.setForeground(new java.awt.Color(204, 255, 255));
        btnSavePembeli.setText("SAVE");
        btnSavePembeli.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));
        btnSavePembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePembeliActionPerformed(evt);
            }
        });
        getContentPane().add(btnSavePembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 98, 36));

        btnCancelPembeli.setBackground(new java.awt.Color(153, 0, 0));
        btnCancelPembeli.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancelPembeli.setForeground(new java.awt.Color(204, 255, 255));
        btnCancelPembeli.setText("CANCEL");
        btnCancelPembeli.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 51, 51)));
        btnCancelPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelPembeliActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 98, 36));

        lblIDKategori.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori.setText("ID Pembeli");
        getContentPane().add(lblIDKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 134, 117, -1));

        lblNamaKategori.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamaKategori.setText("Nama Pembeli");
        getContentPane().add(lblNamaKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 189, -1, 28));

        txtTeleponPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeleponPembeliActionPerformed(evt);
            }
        });
        getContentPane().add(txtTeleponPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 348, 38));

        jJudul1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul1.setText(":");
        getContentPane().add(jJudul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 189, -1, 28));

        jJudul3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul3.setText(":");
        getContentPane().add(jJudul3, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 245, -1, 28));

        lblIDKategori1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori1.setText("No Telepon");
        getContentPane().add(lblIDKategori1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 247, 117, -1));

        lblNamaKategori1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamaKategori1.setText("Alamat");
        getContentPane().add(lblNamaKategori1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 302, -1, 28));

        jJudul5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul5.setText(":");
        getContentPane().add(jJudul5, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 245, -1, 28));

        jJudul4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul4.setText(":");
        getContentPane().add(jJudul4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 10, 28));

        txtNamaPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPembeliActionPerformed(evt);
            }
        });
        getContentPane().add(txtNamaPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 187, 348, 38));

        txtAlamatPembeli.setColumns(20);
        txtAlamatPembeli.setRows(5);
        jScrollPane1.setViewportView(txtAlamatPembeli);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 350, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DialogBG.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 760, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDPembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDPembeliActionPerformed

    private void btnSavePembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePembeliActionPerformed
       String id = txtIDPembeli.getText().trim();
    String nama = txtNamaPembeli.getText().trim();
    String telp = txtTeleponPembeli.getText().trim();
    String alamat = txtAlamatPembeli.getText().trim();

    if (nama.isEmpty() || telp.isEmpty() || alamat.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua field wajib diisi!");
        return;
    }

    if (!isUpdate) {
        dataPembeli = new Pembeli();
        dataPembeli.setIdPembeli(id);
        dataPembeli.setNamaPembeli(nama);
        dataPembeli.setNoTelepon(telp);
        dataPembeli.setAlamat(alamat);

    } else {
        dataPembeli.setNamaPembeli(nama);
        dataPembeli.setNoTelepon(telp);
        dataPembeli.setAlamat(alamat);
    }

    dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSavePembeliActionPerformed

    private void btnCancelPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelPembeliActionPerformed
        dataPembeli = null;
    dispose();
    }//GEN-LAST:event_btnCancelPembeliActionPerformed

    private void txtTeleponPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeleponPembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeleponPembeliActionPerformed

    private void txtNamaPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPembeliActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public Pembeli getPembeli() {
    return dataPembeli;
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelPembeli;
    private javax.swing.JButton btnSavePembeli;
    private javax.swing.JLabel jJudul1;
    private javax.swing.JLabel jJudul2;
    private javax.swing.JLabel jJudul3;
    private javax.swing.JLabel jJudul4;
    private javax.swing.JLabel jJudul5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIDKategori;
    private javax.swing.JLabel lblIDKategori1;
    private javax.swing.JLabel lblNamaKategori;
    private javax.swing.JLabel lblNamaKategori1;
    private javax.swing.JTextArea txtAlamatPembeli;
    private javax.swing.JTextField txtIDPembeli;
    private javax.swing.JTextField txtNamaPembeli;
    private javax.swing.JTextField txtTeleponPembeli;
    // End of variables declaration//GEN-END:variables

   // TARUH DI BAGIAN PALING BAWAH DialogPembeli.java
public Pembeli getResult() {
    return dataPembeli;
}





}
