/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Dialog;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import model.Barang;
import model.DetailRestock;
import model.Restock;
import model.Supplier;
import service.BarangService;
import service.DetailRestockService;
import service.RestockService;
import service.SupplierService;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.JLabel;
import java.awt.Font;
import java.awt.Color;




public class DialogRestock extends javax.swing.JDialog {

     // SERVICE
    private BarangService barangService = new BarangService();
    private SupplierService supplierService = new SupplierService();
    private RestockService restockService = new RestockService();
    private DetailRestockService detailRestockService = new DetailRestockService();

    private List<Barang> listBarang = new ArrayList<>();
    private List<Supplier> listSupplier = new ArrayList<>();

    private DefaultTableModel model;

    private boolean saved = false;
    private String idPegawai;
    private String namaPegawai;

    
    public DialogRestock(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();

    prepareTable();          // 1. SET MODEL DULU
    loadBarang();
    loadSuppliers();

    styleTableHeader(tblItemlRestock); 
    alignTableColumns(tblItemlRestock);  // 2. ALIGN SETELAH MODEL SIAP

    txtIdRestok.setText(restockService.generateIdRestock());
    addSubtotalAutoListener();
}



    
    
     public void setAdminInfo(String idPegawai, String namaPegawai) {
        this.idPegawai = idPegawai;
        this.namaPegawai = namaPegawai;
        txtAdmin.setText(namaPegawai);
    }



      private void loadSuppliers() {
        listSupplier = supplierService.getAll();
        cmbSupplier.removeAllItems();
        for (Supplier s : listSupplier) {
            cmbSupplier.addItem(s.getNamaSupplier());
        }
    }
      
       private void loadBarang() {
        listBarang = barangService.getAll();
        cmnBarang.removeAllItems();
        for (Barang b : listBarang) {
            cmnBarang.addItem(b.getNamaBarang());
        }
    }
       
        private void prepareTable() {
        model = new DefaultTableModel(new Object[]{
            "ID Barang", "Nama Barang", "Harga Beli", "Jumlah", "Subtotal"
        }, 0);
        tblItemlRestock.setModel(model);
    }
    
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIDKategori3 = new javax.swing.JLabel();
        scrollRestocl = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jJudul2 = new javax.swing.JLabel();
        txtIdRestok = new javax.swing.JTextField();
        lblNamaKategori = new javax.swing.JLabel();
        txtAdmin = new javax.swing.JTextField();
        jJudul1 = new javax.swing.JLabel();
        lblIDKategori4 = new javax.swing.JLabel();
        jJudul9 = new javax.swing.JLabel();
        lblNamaKategori2 = new javax.swing.JLabel();
        cmbSupplier = new javax.swing.JComboBox<>();
        lblNamaKategori3 = new javax.swing.JLabel();
        jJudul3 = new javax.swing.JLabel();
        cmnBarang = new javax.swing.JComboBox<>();
        txtHargaBeli = new javax.swing.JTextField();
        lblIDKategori5 = new javax.swing.JLabel();
        jJudul10 = new javax.swing.JLabel();
        lblIDKategori6 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        jJudul11 = new javax.swing.JLabel();
        lblIDKategori7 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        jJudul12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItemlRestock = new javax.swing.JTable();
        btnTambahItem = new javax.swing.JButton();
        btnHapusItem = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIDKategori3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(lblIDKategori3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 134, 117, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 1400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("RESTOCK");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jJudul2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul2.setText(":");
        jPanel1.add(jJudul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 30, 28));

        txtIdRestok.setEditable(false);
        jPanel1.add(txtIdRestok, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 350, 39));

        lblNamaKategori.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamaKategori.setText("Admin");
        jPanel1.add(lblNamaKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, 28));

        txtAdmin.setEditable(false);
        jPanel1.add(txtAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 348, 38));

        jJudul1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul1.setText(":");
        jPanel1.add(jJudul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, 28));

        lblIDKategori4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori4.setText("ID Restock");
        jPanel1.add(lblIDKategori4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 117, -1));

        jJudul9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul9.setText(":");
        jPanel1.add(jJudul9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 10, 28));

        lblNamaKategori2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamaKategori2.setText("Pilih Barang");
        jPanel1.add(lblNamaKategori2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, 28));

        jPanel1.add(cmbSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 350, 40));

        lblNamaKategori3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamaKategori3.setText("Supplier");
        jPanel1.add(lblNamaKategori3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, 28));

        jJudul3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul3.setText(":");
        jPanel1.add(jJudul3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, 28));

        cmnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmnBarangActionPerformed(evt);
            }
        });
        jPanel1.add(cmnBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 350, 40));
        jPanel1.add(txtHargaBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 350, 39));

        lblIDKategori5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori5.setText("Jumlah");
        jPanel1.add(lblIDKategori5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 117, -1));

        jJudul10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul10.setText(":");
        jPanel1.add(jJudul10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 10, 28));

        lblIDKategori6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori6.setText("Harga Beli");
        jPanel1.add(lblIDKategori6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 117, -1));

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });
        jPanel1.add(txtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 350, 39));

        jJudul11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul11.setText(":");
        jPanel1.add(jJudul11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 10, 28));

        lblIDKategori7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori7.setText("Subtotal");
        jPanel1.add(lblIDKategori7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 117, -1));

        txtSubtotal.setEditable(false);
        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });
        jPanel1.add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 350, 39));

        jJudul12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul12.setText(":");
        jPanel1.add(jJudul12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 10, 28));

        tblItemlRestock.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 102)));
        tblItemlRestock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblItemlRestock.setForeground(new java.awt.Color(0, 0, 102));
        tblItemlRestock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Barang", "Nama Barang", "Harga Beli", "Jumlah", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblItemlRestock);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 670, 620, 290));

        btnTambahItem.setBackground(new java.awt.Color(0, 0, 102));
        btnTambahItem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTambahItem.setForeground(new java.awt.Color(204, 255, 255));
        btnTambahItem.setText("TAMBAH ITEM");
        btnTambahItem.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));
        btnTambahItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahItemActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambahItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, 160, 36));

        btnHapusItem.setBackground(new java.awt.Color(153, 0, 0));
        btnHapusItem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHapusItem.setForeground(new java.awt.Color(204, 255, 255));
        btnHapusItem.setText("HAPUS ITEM");
        btnHapusItem.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 0)));
        btnHapusItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusItemActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapusItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, 160, 36));

        btnSimpan.setBackground(new java.awt.Color(0, 0, 102));
        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(204, 255, 255));
        btnSimpan.setText("SIMPAN");
        btnSimpan.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 990, 160, 36));

        btnCancel.setBackground(new java.awt.Color(153, 0, 0));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(204, 255, 255));
        btnCancel.setText("BATALKAN");
        btnCancel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 0)));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 990, 160, 36));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DialogBG.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 900, 1290));

        scrollRestocl.setViewportView(jPanel1);

        getContentPane().add(scrollRestocl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahItemActionPerformed
          int idx = cmnBarang.getSelectedIndex();
    if (idx < 0) {
        JOptionPane.showMessageDialog(this, "Pilih barang dulu!");
        return;
    }

    Barang b = listBarang.get(idx);

    int jumlah;
    double hargaBeli;

    try {
        hargaBeli = Double.parseDouble(txtHargaBeli.getText());
        jumlah = Integer.parseInt(txtJumlah.getText());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Harga/Jumlah tidak valid!");
        return;
    }

    double subtotal = hargaBeli * jumlah;
    String subtotalFormat = String.format("%.0f", subtotal);

    model.addRow(new Object[]{
        b.getIdBarang(),
        b.getNamaBarang(),
        hargaBeli,
        jumlah,
        subtotalFormat
    });

    txtJumlah.setText("");
    txtSubtotal.setText("");

    // === NOTIF TAMBAH ITEM ===
    JOptionPane.showMessageDialog(this,
        "Item berhasil ditambahkan ke daftar!",
        "Informasi", JOptionPane.INFORMATION_MESSAGE);   // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahItemActionPerformed

    private void btnHapusItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusItemActionPerformed
         int row = tblItemlRestock.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Pilih item yang mau dihapus!");
        return;
    }
    
    model.removeRow(row);

    // === NOTIF HAPUS ===
    JOptionPane.showMessageDialog(this,
        "Item berhasil dihapus dari daftar!",
        "Informasi", JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusItemActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
         if (model.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "Belum ada item restock!");
        return;
    }

    int supplierIndex = cmbSupplier.getSelectedIndex();
    if (supplierIndex < 0) {
        JOptionPane.showMessageDialog(this, "Pilih supplier!");
        return;
    }

    Supplier supplier = listSupplier.get(supplierIndex);
    String idRestock = txtIdRestok.getText();

    // HEADER
    Restock r = new Restock();
    r.setIdRestock(idRestock);
    r.setIdPegawai(idPegawai);
    r.setIdSupplier(supplier.getIdSupplier());
    r.setTanggal(new java.sql.Date(System.currentTimeMillis()));
    r.setJumlah(model.getRowCount());

    if (!restockService.insert(r)) {
        JOptionPane.showMessageDialog(this, "Gagal simpan header restock!");
        return;
    }

    // DETAIL
    for (int i = 0; i < model.getRowCount(); i++) {

        String idBarang = model.getValueAt(i, 0).toString();
        int jumlah = Integer.parseInt(model.getValueAt(i, 3).toString());
        double harga = Double.parseDouble(model.getValueAt(i, 2).toString());
        double subtotal = jumlah * harga;

        DetailRestock d = new DetailRestock();
        d.setIdDetailRestock(detailRestockService.generateIdDetailRestock());
        d.setIdRestock(idRestock);
        d.setIdBarang(idBarang);
        d.setHargaBeli(harga);
        d.setJumlah(jumlah);

        detailRestockService.insert(d);

        // UPDATE STOCK
        Barang b = barangService.getById(idBarang);
        barangService.updateStok(idBarang, b.getStock() + jumlah);
    }

    saved = true;
        JOptionPane.showMessageDialog(this,
    "Restock berhasil disimpan!",
    "Sukses", JOptionPane.INFORMATION_MESSAGE);
        
    dispose();    
       // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
         saved = false;
    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
         try {
        int jumlah = Integer.parseInt(txtJumlah.getText());
        double harga = Double.parseDouble(txtHargaBeli.getText());
        txtSubtotal.setText(String.valueOf(jumlah * harga));
    } catch (Exception e) {
        txtSubtotal.setText("");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void cmnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmnBarangActionPerformed
     int index = cmnBarang.getSelectedIndex();
        if (index >= 0) {
            Barang b = listBarang.get(index);
            txtHargaBeli.setText(String.valueOf(b.getHarga()));
        }       // TODO add your handling code here:
    }//GEN-LAST:event_cmnBarangActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnHapusItem;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambahItem;
    private javax.swing.JComboBox<String> cmbSupplier;
    private javax.swing.JComboBox<String> cmnBarang;
    private javax.swing.JLabel jJudul1;
    private javax.swing.JLabel jJudul10;
    private javax.swing.JLabel jJudul11;
    private javax.swing.JLabel jJudul12;
    private javax.swing.JLabel jJudul2;
    private javax.swing.JLabel jJudul3;
    private javax.swing.JLabel jJudul9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIDKategori3;
    private javax.swing.JLabel lblIDKategori4;
    private javax.swing.JLabel lblIDKategori5;
    private javax.swing.JLabel lblIDKategori6;
    private javax.swing.JLabel lblIDKategori7;
    private javax.swing.JLabel lblNamaKategori;
    private javax.swing.JLabel lblNamaKategori2;
    private javax.swing.JLabel lblNamaKategori3;
    private javax.swing.JScrollPane scrollRestocl;
    private javax.swing.JTable tblItemlRestock;
    private javax.swing.JTextField txtAdmin;
    private javax.swing.JTextField txtHargaBeli;
    private javax.swing.JTextField txtIdRestok;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtSubtotal;
    // End of variables declaration//GEN-END:variables

public boolean isSaved() {
    return saved;
}

    private void addSubtotalAutoListener() {

        DocumentListener dl = new DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { hitungSubtotal(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { hitungSubtotal(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { hitungSubtotal(); }

            private void hitungSubtotal() {
        try {
            double harga = Double.parseDouble(txtHargaBeli.getText());
            int jml = Integer.parseInt(txtJumlah.getText());
            double subtotal = harga * jml;

            txtSubtotal.setText(String.format("%.0f", subtotal));
        } catch (Exception e) {
            txtSubtotal.setText("");
        }
    }
        };

        txtHargaBeli.getDocument().addDocumentListener(dl);
        txtJumlah.getDocument().addDocumentListener(dl);
    }

    private void styleTableHeader(JTable table) {
    JTableHeader header = table.getTableHeader();
    header.setFont(new Font("Segoe UI", Font.BOLD, 14));

    header.setBackground(new Color(230, 230, 230));  // abu soft
    header.setForeground(new Color(0, 0, 102));      // biru gelap tema lu

    DefaultTableCellRenderer renderer =
        (DefaultTableCellRenderer) header.getDefaultRenderer();

    renderer.setHorizontalAlignment(JLabel.CENTER);
    renderer.setOpaque(true);
}

    private void alignTableColumns(JTable table) {

    DefaultTableCellRenderer right = new DefaultTableCellRenderer();
    right.setHorizontalAlignment(JLabel.RIGHT);

    DefaultTableCellRenderer center = new DefaultTableCellRenderer();
    center.setHorizontalAlignment(JLabel.CENTER);

    DefaultTableCellRenderer left = new DefaultTableCellRenderer();
    left.setHorizontalAlignment(JLabel.LEFT);

    // Kolom 0 → ID Barang (center)
    table.getColumnModel().getColumn(0).setCellRenderer(center);

    // Kolom 1 → Nama Barang (left)
    table.getColumnModel().getColumn(1).setCellRenderer(left);

    // Kolom 2 → Harga Beli (right)
    table.getColumnModel().getColumn(2).setCellRenderer(right);

    // Kolom 3 → Jumlah (right)
    table.getColumnModel().getColumn(3).setCellRenderer(right);

    // Kolom 4 → Subtotal (right)
    table.getColumnModel().getColumn(4).setCellRenderer(right);
}





}
