/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Dialog;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.DetailRestock;
import service.DetailRestockService;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.JLabel;
import java.awt.Color;
import java.awt.Font;


/**
 *
 * @author ryo not rio
 */


public class DialogDetailRestock extends javax.swing.JDialog {
    private String idRestockGlobal;


    /**
     * Creates new form DialogDetailRestock
     */
public DialogDetailRestock(java.awt.Frame parent, String idRestock) {
    super(parent, true); 
    initComponents();

    this.idRestockGlobal = idRestock; // SIMPAN!

    prepareTable();
    loadDetail(idRestock);

    styleTableHeader(tblDetailRestock);
    alignTableColumns(tblDetailRestock);

    setLocationRelativeTo(parent);
}




    
    private DetailRestockService detailService = new DetailRestockService();
    private DefaultTableModel model;
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetailRestock = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("TOTAL : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 120, -1));

        tblDetailRestock.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 102)));
        tblDetailRestock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblDetailRestock.setForeground(new java.awt.Color(0, 0, 102));
        tblDetailRestock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Barang", "Nama Barang", "Harga Beli", "Jumlah", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblDetailRestock);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 70, 690, 220));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("DETAIL RESTOK BARANG");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 32, -1, -1));

        txtTotal.setEditable(false);
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 160, 30));

        btnClose.setBackground(new java.awt.Color(153, 0, 0));
        btnClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClose.setForeground(new java.awt.Color(204, 255, 255));
        btnClose.setText("CLOSE");
        btnClose.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 51, 51)));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 410, 160, 40));

        btnPrint.setBackground(new java.awt.Color(204, 102, 0));
        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(204, 255, 255));
        btnPrint.setText("PRINT");
        btnPrint.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 153, 51)));
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 410, 160, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DialogBG.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
  try {
        String path = "src/Report/ReportDetailRestok.jrxml";

        java.util.Map<String, Object> params = new java.util.HashMap<>();
        params.put("id_restok", idRestockGlobal);   // INI YANG PALING PENTING

        report.ReportUtil.showReport(path, params);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Gagal mencetak laporan: " + e.getMessage());
    }    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void prepareTable() {
    model = new DefaultTableModel(new Object[]{
        "ID Barang", "Nama Barang", "Harga Beli", "Jumlah", "Subtotal"
    }, 0);

    tblDetailRestock.setModel(model);
    tblDetailRestock.setEnabled(false); // read only
}

    public void loadDetail(String idRestock) {
    model.setRowCount(0);
    double total = 0;

    for (DetailRestock d : detailService.getByRestock(idRestock)) {

        double subtotal = d.getSubtotal();
        String subtotalFormat = String.format("%.0f", subtotal);

        model.addRow(new Object[]{
            d.getIdBarang(),
            d.getNamaBarang(),
            d.getHargaBeli(),
            d.getJumlah(),
            subtotalFormat
        });

        total += subtotal;
    }

    txtTotal.setText(String.format("%.0f", total));
}

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDetailRestock;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

   private void styleTableHeader(JTable table) {
    JTableHeader header = table.getTableHeader();
    header.setFont(new Font("Segoe UI", Font.BOLD, 14));

    header.setBackground(new Color(230, 230, 230));   // abu soft
    header.setForeground(new Color(0, 0, 102));       // warna teks biru tema lu

    DefaultTableCellRenderer renderer =
        (DefaultTableCellRenderer) header.getDefaultRenderer();

    renderer.setHorizontalAlignment(JLabel.CENTER);
    renderer.setOpaque(true);
}

    private void alignTableColumns(JTable table) {

    // Renderer untuk align
    DefaultTableCellRenderer right = new DefaultTableCellRenderer();
    right.setHorizontalAlignment(JLabel.RIGHT);

    DefaultTableCellRenderer center = new DefaultTableCellRenderer();
    center.setHorizontalAlignment(JLabel.CENTER);

    DefaultTableCellRenderer left = new DefaultTableCellRenderer();
    left.setHorizontalAlignment(JLabel.LEFT);

    // Kolom 0 -> ID Barang (center)
    table.getColumnModel().getColumn(0).setCellRenderer(center);

    // Kolom 1 -> Nama Barang (left)
    table.getColumnModel().getColumn(1).setCellRenderer(left);

    // Kolom 2 -> Harga Beli (right)
    table.getColumnModel().getColumn(2).setCellRenderer(right);

    // Kolom 3 -> Jumlah (right)
    table.getColumnModel().getColumn(3).setCellRenderer(right);

    // Kolom 4 -> Subtotal (right)
    table.getColumnModel().getColumn(4).setCellRenderer(right);
}



}
