/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Dialog;

import javax.swing.JOptionPane;
import service.KategoriService;

/**
 *
 * @author ryo not rio
 */

public class DialogKategori extends javax.swing.JDialog {
private model.Kategori result = null;
private boolean isUpdate = false;

public model.Kategori getResult() {
    return result;
}

    
public void setInsertMode() {
    isUpdate = false;

    txtIDKategori.setEditable(true);
    txtNamaKategori.setEditable(true);

    txtIDKategori.setText(generateID());
    txtNamaKategori.setText("");

    btnSaveKategori.setText("SAVE");
}

public void setUpdateMode(model.Kategori k) {
    isUpdate = true;

    txtIDKategori.setEditable(false);
    txtNamaKategori.setEditable(true);

    txtIDKategori.setText(k.getIdKategori());
    txtNamaKategori.setText(k.getNamaKategori());

    result = k;

    btnSaveKategori.setText("UPDATE");
}
/**
     * Creates new form DialogKategori
     */
    
    public DialogKategori(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIDKategori = new javax.swing.JTextField();
        btnCancelKategori = new javax.swing.JButton();
        lblIDKategori = new javax.swing.JLabel();
        lblNamaKategori = new javax.swing.JLabel();
        txtNamaKategori = new javax.swing.JTextField();
        jJudul1 = new javax.swing.JLabel();
        jJudul2 = new javax.swing.JLabel();
        btnSaveKategori = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("KATEGORI BARANG");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 24, -1, -1));

        txtIDKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDKategoriActionPerformed(evt);
            }
        });
        getContentPane().add(txtIDKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 130, 350, 39));

        btnCancelKategori.setBackground(new java.awt.Color(153, 0, 0));
        btnCancelKategori.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancelKategori.setForeground(new java.awt.Color(204, 255, 255));
        btnCancelKategori.setText("CANCEL");
        btnCancelKategori.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 51, 51)));
        btnCancelKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelKategoriActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 286, 98, 36));

        lblIDKategori.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori.setText("ID Kategori");
        getContentPane().add(lblIDKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 134, 117, -1));

        lblNamaKategori.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamaKategori.setText("Nama Kategori");
        getContentPane().add(lblNamaKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 189, -1, 28));

        txtNamaKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaKategoriActionPerformed(evt);
            }
        });
        getContentPane().add(txtNamaKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 187, 350, 38));

        jJudul1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul1.setText(":");
        getContentPane().add(jJudul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 189, -1, 28));

        jJudul2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul2.setText(":");
        getContentPane().add(jJudul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 132, -1, 28));

        btnSaveKategori.setBackground(new java.awt.Color(0, 0, 102));
        btnSaveKategori.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSaveKategori.setForeground(new java.awt.Color(204, 255, 255));
        btnSaveKategori.setText("SAVE");
        btnSaveKategori.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));
        btnSaveKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveKategoriActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaveKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 286, 98, 36));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DialogBG.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDKategoriActionPerformed

    private void btnCancelKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelKategoriActionPerformed
        result = null;
    dispose();
    }//GEN-LAST:event_btnCancelKategoriActionPerformed

    private void txtNamaKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaKategoriActionPerformed

    private void btnSaveKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveKategoriActionPerformed
     String nama = txtNamaKategori.getText().trim();
    String id = txtIDKategori.getText().trim();

    KategoriService service = new KategoriService();

    // VALIDASI DASAR
    if (nama.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nama kategori wajib diisi!");
        return;
    }

    // VALIDASI PK DUPLIKAT (HANYA INSERT MODE)
    if (!isUpdate) {
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID kategori wajib diisi!");
            return;
        }

        if (service.existsById(id)) {
            JOptionPane.showMessageDialog(this,
                    "ID kategori sudah digunakan! Masukkan ID lain.");
            return; // form tetep stay
        }
    }

    boolean success = false;

    try {
        if (!isUpdate) {
            // INSERT MODE
            model.Kategori k = new model.Kategori();
            k.setIdKategori(id);
            k.setNamaKategori(nama);
            result = k;

        } else {
            // UPDATE MODE
            result.setNamaKategori(nama);
        }

        success = true;

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Terjadi kesalahan saat menyimpan kategori: " + e.getMessage());
    }

    // FORM TUTUP HANYA KALAU BENAR-BENAR SUKSES
    if (success) {
        dispose();
    }     // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveKategoriActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelKategori;
    private javax.swing.JButton btnSaveKategori;
    private javax.swing.JLabel jJudul1;
    private javax.swing.JLabel jJudul2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblIDKategori;
    private javax.swing.JLabel lblNamaKategori;
    private javax.swing.JTextField txtIDKategori;
    private javax.swing.JTextField txtNamaKategori;
    // End of variables declaration//GEN-END:variables

    private String generateID() {
      return "K" + (int)(Math.random() * 900 + 100);  
    }
}
