
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Dialog;

import java.awt.Frame;
import javax.swing.JOptionPane;
import model.JenisPembayaran;
import service.JenisPembayaranService;

/**
 *
 * @author ryo not rio
 */

public class DialogJenisPembayaran extends javax.swing.JDialog {

 private JenisPembayaran dataEdit; 
   /**
     * Creates new form DialogJenisPembayaran
     */
    public DialogJenisPembayaran(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }
    public DialogJenisPembayaran(Frame parent, JenisPembayaran dataEdit) {
    super(parent, true);
    initComponents();
    setLocationRelativeTo(null);
    
    this.dataEdit = dataEdit;

    if (dataEdit != null) { // MODE EDIT
        txtIdJenis.setText(dataEdit.getIdJenis());
        txtNamaJenis.setText(dataEdit.getNamaJenis());
        txtKeterangan.setText(dataEdit.getKeterangan());

        txtIdJenis.setEnabled(false); // id ga boleh berubah
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jJudul2 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtIdJenis = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        lblIDKategori = new javax.swing.JLabel();
        lblNamaKategori = new javax.swing.JLabel();
        txtNamaJenis = new javax.swing.JTextField();
        jJudul1 = new javax.swing.JLabel();
        lblNamaKategori1 = new javax.swing.JLabel();
        jJudul3 = new javax.swing.JLabel();
        txtKeterangan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jJudul2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul2.setText(":");
        getContentPane().add(jJudul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 132, 17, 28));

        btnSimpan.setBackground(new java.awt.Color(0, 0, 102));
        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(204, 255, 255));
        btnSimpan.setText("SAVE");
        btnSimpan.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 376, 98, 36));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("JENIS PEMBAYARAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 26, -1, -1));

        txtIdJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdJenisActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 130, 350, 39));

        btnBatal.setBackground(new java.awt.Color(153, 0, 0));
        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(204, 255, 255));
        btnBatal.setText("CANCEL");
        btnBatal.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 51, 51)));
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 376, 98, 36));

        lblIDKategori.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori.setText("ID Jenis");
        getContentPane().add(lblIDKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 134, 117, -1));

        lblNamaKategori.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamaKategori.setText("Nama Jenis");
        getContentPane().add(lblNamaKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 189, -1, 28));

        txtNamaJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaJenisActionPerformed(evt);
            }
        });
        getContentPane().add(txtNamaJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 187, 350, 38));

        jJudul1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul1.setText(":");
        getContentPane().add(jJudul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 189, 17, 28));

        lblNamaKategori1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamaKategori1.setText("Keterangan ");
        getContentPane().add(lblNamaKategori1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 245, -1, 28));

        jJudul3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul3.setText(":");
        getContentPane().add(jJudul3, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 245, 17, 28));

        txtKeterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeteranganActionPerformed(evt);
            }
        });
        getContentPane().add(txtKeterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 243, 350, 38));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DialogBG.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
         String id = txtIdJenis.getText().trim();
    String nama = txtNamaJenis.getText().trim();
    String ket = txtKeterangan.getText().trim();

    JenisPembayaranService service = new JenisPembayaranService();

    // VALIDASI KOSONG
    if (id.isEmpty() || nama.isEmpty()) {
        JOptionPane.showMessageDialog(this, "ID dan Nama wajib diisi!");
        return;
    }

    // CEK DUPLIKAT (HANYA INSERT)
    if (dataEdit == null && service.existsById(id)) {
        JOptionPane.showMessageDialog(this,
                "ID sudah digunakan! Gunakan ID lain.");
        return;
    }

    // UPDATE MODE → ubah object existing
    if (dataEdit != null) {
        dataEdit.setNamaJenis(nama);
        dataEdit.setKeterangan(ket);
    }

    // INSERT MODE → biarkan getResult() yang membuat object
    dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtIdJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdJenisActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        this.dispose();

    }//GEN-LAST:event_btnBatalActionPerformed

    private void txtNamaJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaJenisActionPerformed

    private void txtKeteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeteranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeteranganActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jJudul1;
    private javax.swing.JLabel jJudul2;
    private javax.swing.JLabel jJudul3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblIDKategori;
    private javax.swing.JLabel lblNamaKategori;
    private javax.swing.JLabel lblNamaKategori1;
    private javax.swing.JTextField txtIdJenis;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtNamaJenis;
    // End of variables declaration//GEN-END:variables

    public JenisPembayaran getResult() {
    if (dataEdit != null) {
        // MODE UPDATE → return object yang sudah diubah
        return dataEdit;
    }

    // MODE INSERT → buat object baru
    return new JenisPembayaran(
        txtIdJenis.getText().trim(),
        txtNamaJenis.getText().trim(),
        txtKeterangan.getText().trim()
    );
}


    public void setUpdateMode(JenisPembayaran jp) {
    this.dataEdit = jp;

    txtIdJenis.setText(jp.getIdJenis());
    txtNamaJenis.setText(jp.getNamaJenis());
    txtKeterangan.setText(jp.getKeterangan());

    txtIdJenis.setEnabled(false); // ID tidak boleh berubah
}

}
