/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Dialog;

import java.util.List;
import javax.swing.JOptionPane;
import model.Barang;
import model.Kategori;
import service.BarangService;
import service.KategoriService;

/**
 *
 * @author ryo not rio
 */
public class DialogBarang extends javax.swing.JDialog {
    private boolean isUpdate = false;
private Barang dataBarang;     // hasil dialog
private List<Kategori> listKategori; // buat isi combobox


    /**
     * Creates new form DialogBarang
     */
    public DialogBarang(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadComboKategori();

    }
    
    public void setInsertMode(List<Kategori> kategoriList) {
    isUpdate = false;
    this.listKategori = kategoriList;

    txtIDBarang.setEditable(true);
    txtNamaBarang.setEditable(true);
    txtHargaBarang.setEditable(true);
    txtStokBarang.setEditable(true);

    cmbKategoriBarang.removeAllItems();
    for (Kategori k : kategoriList) {
cmbKategoriBarang.addItem(k.getNamaKategori());
    }

    btnSaveBarang.setText("SAVE");
}

    
        public void setUpdateMode(Barang barang, List<Kategori> kategoriList) {
    isUpdate = true;
    this.dataBarang = barang;
    this.listKategori = kategoriList;

    txtIDBarang.setText(barang.getIdBarang());
    txtIDBarang.setEditable(false);

    txtNamaBarang.setText(barang.getNamaBarang());
    txtHargaBarang.setText(String.valueOf(barang.getHarga()));
    txtStokBarang.setText(String.valueOf(barang.getStock()));

    cmbKategoriBarang.removeAllItems();
    for (Kategori k : kategoriList) {cmbKategoriBarang.addItem(k.getNamaKategori());

    }

    // Pilih kategori yang sesuai
    for (int i = 0; i < listKategori.size(); i++) {
        if (listKategori.get(i).getIdKategori().equals(barang.getIdKategori())) {
            cmbKategoriBarang.setSelectedIndex(i);
            break;
        }
    }

    btnSaveBarang.setText("UPDATE");
}

          

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jJudul2 = new javax.swing.JLabel();
        txtIDBarang = new javax.swing.JTextField();
        btnSaveBarang = new javax.swing.JButton();
        btnCancelBarang = new javax.swing.JButton();
        lblIDKategori = new javax.swing.JLabel();
        lblNamaKategori = new javax.swing.JLabel();
        txtNamaBarang = new javax.swing.JTextField();
        jJudul1 = new javax.swing.JLabel();
        jJudul3 = new javax.swing.JLabel();
        lblIDKategori1 = new javax.swing.JLabel();
        lblNamaKategori1 = new javax.swing.JLabel();
        txtHargaBarang = new javax.swing.JTextField();
        jJudul5 = new javax.swing.JLabel();
        jJudul4 = new javax.swing.JLabel();
        jJudul6 = new javax.swing.JLabel();
        txtStokBarang = new javax.swing.JTextField();
        lblIDKategori2 = new javax.swing.JLabel();
        jJudul7 = new javax.swing.JLabel();
        cmbKategoriBarang = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("BARANG");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 36, -1, -1));

        jJudul2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul2.setText(":");
        getContentPane().add(jJudul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 132, -1, 28));

        txtIDBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDBarangActionPerformed(evt);
            }
        });
        getContentPane().add(txtIDBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 130, 350, 39));

        btnSaveBarang.setBackground(new java.awt.Color(0, 0, 102));
        btnSaveBarang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSaveBarang.setForeground(new java.awt.Color(204, 255, 255));
        btnSaveBarang.setText("SAVE");
        btnSaveBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));
        btnSaveBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBarangActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaveBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 98, 36));

        btnCancelBarang.setBackground(new java.awt.Color(153, 0, 0));
        btnCancelBarang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancelBarang.setForeground(new java.awt.Color(204, 255, 255));
        btnCancelBarang.setText("CANCEL");
        btnCancelBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 51, 51)));
        btnCancelBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelBarangActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 98, 36));

        lblIDKategori.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori.setText("ID Barang");
        getContentPane().add(lblIDKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 134, 117, -1));

        lblNamaKategori.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamaKategori.setText("Nama Barang");
        getContentPane().add(lblNamaKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 189, -1, 28));

        txtNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaBarangActionPerformed(evt);
            }
        });
        getContentPane().add(txtNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 187, 348, 38));

        jJudul1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul1.setText(":");
        getContentPane().add(jJudul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 189, -1, 28));

        jJudul3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul3.setText(":");
        getContentPane().add(jJudul3, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 245, -1, 28));

        lblIDKategori1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori1.setText("Kategori");
        getContentPane().add(lblIDKategori1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 247, 117, -1));

        lblNamaKategori1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamaKategori1.setText("Harga");
        getContentPane().add(lblNamaKategori1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 302, -1, 28));

        txtHargaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaBarangActionPerformed(evt);
            }
        });
        getContentPane().add(txtHargaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 300, 348, 38));

        jJudul5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul5.setText(":");
        getContentPane().add(jJudul5, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 245, -1, 28));

        jJudul4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul4.setText(":");
        getContentPane().add(jJudul4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 10, 28));

        jJudul6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul6.setText(":");
        getContentPane().add(jJudul6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, 28));

        txtStokBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStokBarangActionPerformed(evt);
            }
        });
        getContentPane().add(txtStokBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 350, 39));

        lblIDKategori2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori2.setText("Stok");
        getContentPane().add(lblIDKategori2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 117, -1));

        jJudul7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul7.setText(":");
        getContentPane().add(jJudul7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, 28));

        cmbKategoriBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKategoriBarangActionPerformed(evt);
            }
        });
        getContentPane().add(cmbKategoriBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 350, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DialogBG.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 730, 660));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 630));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDBarangActionPerformed

    private void btnSaveBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBarangActionPerformed
       String id = txtIDBarang.getText().trim();
    String nama = txtNamaBarang.getText().trim();
    String hargaTxt = txtHargaBarang.getText().trim();
    String stokTxt = txtStokBarang.getText().trim();
    int indexKategori = cmbKategoriBarang.getSelectedIndex();

    // VALIDASI KOSONG
    if (id.isEmpty() || nama.isEmpty() || hargaTxt.isEmpty() || stokTxt.isEmpty() || indexKategori < 0) {
        JOptionPane.showMessageDialog(this, "Semua field wajib diisi!");
        return;
    }

    // CEK PK DUPLIKAT (HANYA MODE INSERT)
    if (!isUpdate) {
        BarangService service = new BarangService();
        if (service.existsById(id)) {
            JOptionPane.showMessageDialog(this,
                "ID Barang sudah digunakan! Gunakan ID yang berbeda.");
            return; // FORM TETAP STAY, INI YANG LU MAU
        }
    }

    double harga;
    int stok;

    // VALIDASI ANGKA
    try {
        harga = Double.parseDouble(hargaTxt);
        stok = Integer.parseInt(stokTxt);

        if (harga <= 0) {
            JOptionPane.showMessageDialog(this, "Harga harus lebih dari 0!");
            return;
        }

        if (stok < 0) {
            JOptionPane.showMessageDialog(this, "Stok tidak boleh minus!");
            return;
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Harga dan Stok harus berupa angka!");
        return;
    }

    // VALIDASI KATEGORI
    if (indexKategori < 0 || indexKategori >= listKategori.size()) {
        JOptionPane.showMessageDialog(this, "Kategori tidak valid!");
        return;
    }

    Kategori selected = listKategori.get(indexKategori);

    boolean success = false;

    try {
        if (!isUpdate) {
            dataBarang = new Barang(id, selected.getIdKategori(), nama, harga, stok);
        } else {
            dataBarang.setIdKategori(selected.getIdKategori());
            dataBarang.setNamaBarang(nama);
            dataBarang.setHarga(harga);
            dataBarang.setStock(stok);
        }

        success = true;

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Terjadi kesalahan saat menyimpan data barang: " + e.getMessage());
    }

    if (success) {
        dispose();
    }  // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveBarangActionPerformed

    private void btnCancelBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelBarangActionPerformed
        dataBarang = null;
    dispose();
    }//GEN-LAST:event_btnCancelBarangActionPerformed

    private void txtNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaBarangActionPerformed

    private void txtHargaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaBarangActionPerformed

    private void txtStokBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStokBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStokBarangActionPerformed

    private void cmbKategoriBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKategoriBarangActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_cmbKategoriBarangActionPerformed

    /**
     * @param args the command line arguments
     */

    public Barang getBarang() {
    return dataBarang;
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelBarang;
    private javax.swing.JButton btnSaveBarang;
    private javax.swing.JComboBox<String> cmbKategoriBarang;
    private javax.swing.JLabel jJudul1;
    private javax.swing.JLabel jJudul2;
    private javax.swing.JLabel jJudul3;
    private javax.swing.JLabel jJudul4;
    private javax.swing.JLabel jJudul5;
    private javax.swing.JLabel jJudul6;
    private javax.swing.JLabel jJudul7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblIDKategori;
    private javax.swing.JLabel lblIDKategori1;
    private javax.swing.JLabel lblIDKategori2;
    private javax.swing.JLabel lblNamaKategori;
    private javax.swing.JLabel lblNamaKategori1;
    private javax.swing.JTextField txtHargaBarang;
    private javax.swing.JTextField txtIDBarang;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtStokBarang;
    // End of variables declaration//GEN-END:variables

    
 private void loadComboKategori() {
    cmbKategoriBarang.removeAllItems();
    KategoriService service = new KategoriService();

    listKategori = service.getAll();  // <<< Tambahkan di sini

    for (Kategori k : listKategori) {
cmbKategoriBarang.addItem(k.getNamaKategori());

    }
}

    public Barang getResult() {
    return dataBarang;
}


}

