/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Dialog;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import util.DBConnection;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.JLabel;
import java.awt.Color;
import java.awt.Font;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;




/**
 *
 * @author ryo not rio
 */
public class DialogDetailPenjualan extends javax.swing.JDialog {

    /**
     * Creates new form DialogDetailPenjualan
     */
    
    private String idPenjualan;

    public DialogDetailPenjualan(java.awt.Frame parent, String idPenjualan) {
    super(parent, false);   // NON MODAL BIAR REPORT GAK NGEFREEZE
    initComponents();

    this.idPenjualan = idPenjualan;
    setLocationRelativeTo(parent);

    styleTableHeader(tblDetailPenjualan);
    alignTableColumns(tblDetailPenjualan);

    loadDetail();
    hitungTotal();
}




    public DialogDetailPenjualan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetailPenjualan = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("TOTAL : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 420, 120, -1));

        tblDetailPenjualan.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 102)));
        tblDetailPenjualan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblDetailPenjualan.setForeground(new java.awt.Color(0, 0, 102));
        tblDetailPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Barang", "Nama Barang", "Harga", "Jumlah", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblDetailPenjualan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 690, 220));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("DETAIL BARANG TERJUAL");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("DETAIL BARANG TERJUAL");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        txtTotal.setEditable(false);
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 160, 30));

        btnClose.setBackground(new java.awt.Color(153, 0, 0));
        btnClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClose.setForeground(new java.awt.Color(204, 255, 255));
        btnClose.setText("CLOSE");
        btnClose.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 51, 51)));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 160, 40));

        btnPrint.setBackground(new java.awt.Color(204, 102, 0));
        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(204, 255, 255));
        btnPrint.setText("PRINT");
        btnPrint.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 153, 51)));
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, 160, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DialogBG.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
     if (idPenjualan == null || idPenjualan.isEmpty()) {
        JOptionPane.showMessageDialog(this, "ID Penjualan tidak ditemukan!");
        return;
    }

    Map<String, Object> params = new HashMap<>();
    params.put("id_penjualan", idPenjualan);

    String path = "src/Report/ReportDetailPenjualan.jrxml";

    report.ReportUtil.showReport(path, params);
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDetailPenjualan;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void hitungTotal() {
    DefaultTableModel model = (DefaultTableModel) tblDetailPenjualan.getModel();
    double total = 0;

    for (int i = 0; i < model.getRowCount(); i++) {
        total += Double.parseDouble(model.getValueAt(i, 4).toString());
    }

    txtTotal.setText(String.valueOf(total));
}


private void loadDetail() {
    DefaultTableModel model = (DefaultTableModel) tblDetailPenjualan.getModel();
    model.setRowCount(0);

    String sql = """
        SELECT d.id_barang, b.nama_barang, b.harga, d.jumlah,
               (d.jumlah * b.harga) AS subtotal
        FROM detail_penjualan d
        JOIN barang b ON d.id_barang = b.id_barang
        WHERE d.id_penjualan = ?
    """;

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setString(1, idPenjualan);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_barang"),
                rs.getString("nama_barang"),
                rs.getDouble("harga"),
                rs.getInt("jumlah"),
                rs.getDouble("subtotal")
            });
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}

private void styleTableHeader(JTable table) {
    JTableHeader header = table.getTableHeader();
    header.setFont(new Font("Segoe UI", Font.BOLD, 14));

    header.setBackground(new Color(230, 230, 230));  // background abu soft
    header.setForeground(new Color(0, 0, 102));      // warna teks sesuai tema

    DefaultTableCellRenderer renderer =
        (DefaultTableCellRenderer) header.getDefaultRenderer();

    renderer.setHorizontalAlignment(JLabel.CENTER);
    renderer.setOpaque(true);
}

    private void alignTableColumns(JTable table) {

    DefaultTableCellRenderer right = new DefaultTableCellRenderer();
    right.setHorizontalAlignment(JLabel.RIGHT);

    DefaultTableCellRenderer center = new DefaultTableCellRenderer();
    center.setHorizontalAlignment(JLabel.CENTER);

    DefaultTableCellRenderer left = new DefaultTableCellRenderer();
    left.setHorizontalAlignment(JLabel.LEFT);

    // Kolom 0 -> ID Barang (center)
    table.getColumnModel().getColumn(0).setCellRenderer(center);

    // Kolom 1 -> Nama Barang (left)
    table.getColumnModel().getColumn(1).setCellRenderer(left);

    // Kolom 2 -> Harga (right)
    table.getColumnModel().getColumn(2).setCellRenderer(right);

    // Kolom 3 -> Jumlah (right)
    table.getColumnModel().getColumn(3).setCellRenderer(right);

    // Kolom 4 -> Subtotal (right)
    table.getColumnModel().getColumn(4).setCellRenderer(right);
}



}
