/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Dialog;


import java.time.LocalDate;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import util.DBConnection;
import util.IdGenerator;
import service.JenisPembayaranService;
import model.JenisPembayaran;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import service.PembayaranService;




/**
 *
 * @author ryo not rio
 */
public class DialogPembayaran extends javax.swing.JDialog {

    /**
     * Creates new form DialogPembayaran
     */
   
    
  private JTable tableKeranjang;
  private String namaKasir;


public DialogPembayaran(java.awt.Frame parent, String idPenjualan, double total, JTable keranjang, String namaKasir) {
    super(parent, true);
    initComponents();

    this.tableKeranjang = keranjang;
    this.namaKasir = namaKasir;

    txtIdPembayaran.setEditable(false);
    txtIdPenjualan.setEditable(false);
    txtTotal.setEditable(false);
    txtTanggal.setEditable(false);
    txtKembalian.setEditable(false);

    generateIdPembayaran();
    txtIdPenjualan.setText(idPenjualan);
    txtTotal.setText(String.valueOf(total));
    txtTanggal.setText(LocalDate.now().toString());

    loadMetodePembayaran();
}





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdPenjualan = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblIDKategori = new javax.swing.JLabel();
        lblNamaKategori = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblIDKategori1 = new javax.swing.JLabel();
        lblNamaKategori1 = new javax.swing.JLabel();
        lblIDKategori2 = new javax.swing.JLabel();
        cmbMetodePembayaran = new javax.swing.JComboBox<>();
        lblIDKategori3 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        lblIDKategori4 = new javax.swing.JLabel();
        lblIDKategori5 = new javax.swing.JLabel();
        lblIDKategori6 = new javax.swing.JLabel();
        lblIDKategori7 = new javax.swing.JLabel();
        lblIDKategori8 = new javax.swing.JLabel();
        txtJumlahBayar = new javax.swing.JTextField();
        lblIDKategori9 = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();
        btnCetakStruk = new javax.swing.JButton();
        lblIDKategori10 = new javax.swing.JLabel();
        txtIdPembayaran = new javax.swing.JTextField();
        lblIDKategori11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("FORM PEMBAYARAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        txtIdPenjualan.setEditable(false);
        txtIdPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPenjualanActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 149, 350, 39));

        btnSave.setBackground(new java.awt.Color(0, 0, 102));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(204, 255, 255));
        btnSave.setText("SAVE");
        btnSave.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 590, 98, 36));

        btnCancel.setBackground(new java.awt.Color(153, 0, 0));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(204, 255, 255));
        btnCancel.setText("BACK");
        btnCancel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 51, 51)));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, 98, 36));

        lblIDKategori.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori.setText("ID Penjualan");
        getContentPane().add(lblIDKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 153, 117, -1));

        lblNamaKategori.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamaKategori.setText("Total");
        getContentPane().add(lblNamaKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 223, -1, 28));

        txtTotal.setEditable(false);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 221, 348, 38));

        lblIDKategori1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori1.setText("Tanggal");
        getContentPane().add(lblIDKategori1, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 294, 96, -1));

        lblNamaKategori1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamaKategori1.setText("Metode Pembayaran ");
        getContentPane().add(lblNamaKategori1, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 374, -1, 28));

        lblIDKategori2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori2.setText("Kembalian");
        getContentPane().add(lblIDKategori2, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 522, 117, -1));

        cmbMetodePembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMetodePembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(cmbMetodePembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 371, 350, 40));

        lblIDKategori3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori3.setText(":");
        getContentPane().add(lblIDKategori3, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 153, 23, -1));

        txtTanggal.setEditable(false);
        txtTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalActionPerformed(evt);
            }
        });
        getContentPane().add(txtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 290, 348, 38));

        lblIDKategori4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori4.setText("Jumlah Bayar");
        getContentPane().add(lblIDKategori4, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 452, 117, -1));

        lblIDKategori5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori5.setText(":");
        getContentPane().add(lblIDKategori5, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 225, 23, -1));

        lblIDKategori6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori6.setText(":");
        getContentPane().add(lblIDKategori6, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 376, 12, -1));

        lblIDKategori7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori7.setText(":");
        getContentPane().add(lblIDKategori7, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 294, 23, -1));

        lblIDKategori8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori8.setText(":");
        getContentPane().add(lblIDKategori8, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 452, 23, -1));

        txtJumlahBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahBayarActionPerformed(evt);
            }
        });
        txtJumlahBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJumlahBayarKeyReleased(evt);
            }
        });
        getContentPane().add(txtJumlahBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 448, 348, 38));

        lblIDKategori9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori9.setText(":");
        getContentPane().add(lblIDKategori9, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 522, 23, -1));

        txtKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKembalianActionPerformed(evt);
            }
        });
        txtKembalian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKembalianKeyReleased(evt);
            }
        });
        getContentPane().add(txtKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 518, 348, 38));

        btnCetakStruk.setBackground(new java.awt.Color(204, 102, 0));
        btnCetakStruk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCetakStruk.setForeground(new java.awt.Color(204, 255, 255));
        btnCetakStruk.setText("CETAK STRUK");
        btnCetakStruk.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 204, 0)));
        btnCetakStruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakStrukActionPerformed(evt);
            }
        });
        getContentPane().add(btnCetakStruk, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 668, 350, 36));

        lblIDKategori10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori10.setText("ID Pembayaran");
        getContentPane().add(lblIDKategori10, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 86, 161, -1));

        txtIdPembayaran.setEditable(false);
        txtIdPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 82, 350, 39));

        lblIDKategori11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori11.setText(":");
        getContentPane().add(lblIDKategori11, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 86, 23, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DialogBG.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 800, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // =========================
    // VALIDASI AWAL
    // =========================
    String idPembayaran = txtIdPembayaran.getText().trim();
    String idPenjualan = txtIdPenjualan.getText().trim();
    String jenis = getSelectedJenis();
    String jumlahTxt = txtJumlahBayar.getText().trim();

    if (idPembayaran.isEmpty() || idPenjualan.isEmpty() || jenis == null || jumlahTxt.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua field wajib diisi!");
        return;
    }

    // VALIDASI PK DUPLIKAT
    PembayaranService service = new PembayaranService();
    if (service.existsById(idPembayaran)) {
        JOptionPane.showMessageDialog(this, 
            "ID Pembayaran sudah digunakan! Masukkan ID yang berbeda.");
        return; // FORM STAY
    }

    // VALIDASI JUMLAH BAYAR
    double jumlahBayar = 0;
    try {
        jumlahBayar = Double.parseDouble(jumlahTxt);
        if (jumlahBayar <= 0) {
            JOptionPane.showMessageDialog(this, "Jumlah bayar harus lebih dari 0!");
            return;
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Jumlah bayar tidak valid!");
        return;
    }

    boolean success = false;

    String sql = "INSERT INTO pembayaran(id_pembayaran, id_penjualan, id_jenis, tanggal_pembayaran, jumlah_bayar) "
               + "VALUES(?, ?, ?, ?, ?)";

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {

        // INSERT PEMBAYARAN
        ps.setString(1, idPembayaran);
        ps.setString(2, idPenjualan);
        ps.setString(3, jenis);
        ps.setDate(4, java.sql.Date.valueOf(LocalDate.now()));
        ps.setDouble(5, jumlahBayar);
        ps.executeUpdate();

        // UPDATE STATUS PENJUALAN
        updateStatusPenjualanLunas();

        // UPDATE STOK BARANG
        DefaultTableModel model = (DefaultTableModel) tableKeranjang.getModel();

        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Keranjang kosong! Tidak ada barang untuk dikurangi stoknya.");
            return;
        }

        String sqlStok = "UPDATE barang SET stock = stock - ? WHERE id_barang=?";
        PreparedStatement psStok = conn.prepareStatement(sqlStok);

        for (int i = 0; i < model.getRowCount(); i++) {
            String idBarang = model.getValueAt(i, 0).toString();
            int jumlah = Integer.parseInt(model.getValueAt(i, 3).toString());

            psStok.setInt(1, jumlah);
            psStok.setString(2, idBarang);
            psStok.executeUpdate();
        }

        // ================================
        // SIMPAN DETAIL PENJUALAN
        // ================================
        String sqlDetail = "INSERT INTO detail_penjualan " +
                "(id_detail_penjualan, id_penjualan, id_barang, jumlah, subtotal) " +
                "VALUES (?, ?, ?, ?, ?)";

        PreparedStatement psDetail = conn.prepareStatement(sqlDetail);

        for (int i = 0; i < model.getRowCount(); i++) {

            String idBarang = model.getValueAt(i, 0).toString();
            int jumlah = Integer.parseInt(model.getValueAt(i, 3).toString());
            double harga = Double.parseDouble(model.getValueAt(i, 2).toString());
            double subtotal = jumlah * harga;

            // generate ID DETAIL
            String idDetail = IdGenerator.generateId(conn,
                    "detail_penjualan", "id_detail_penjualan", "DP");

            psDetail.setString(1, idDetail);
            psDetail.setString(2, idPenjualan);
            psDetail.setString(3, idBarang);
            psDetail.setInt(4, jumlah);
            psDetail.setDouble(5, subtotal);

            psDetail.executeUpdate();
        }

        JOptionPane.showMessageDialog(this,
            "Pembayaran berhasil disimpan!\nSilakan cetak struk.");

        success = true;

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }

    // =============================
    // JANGAN CLOSE FORM
    // AKTIFKAN TOMBOL CETAK STRUK
    // =============================
    if (success) {
        btnCetakStruk.setEnabled(true);
    }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void cmbMetodePembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMetodePembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMetodePembayaranActionPerformed

    private void txtTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalActionPerformed

    private void txtJumlahBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahBayarActionPerformed

    private void txtKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKembalianActionPerformed

    private void btnCetakStrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakStrukActionPerformed
         String idBayar = txtIdPembayaran.getText();

    if (idBayar.isEmpty()) {
        JOptionPane.showMessageDialog(this, "ID Pembayaran kosong!");
        return;
    }

    Map<String, Object> params = new HashMap<>();
params.put("id_pembayaran", idBayar);
params.put("nama_kasir", this.namaKasir);
params.put("tanggal_struk", LocalDate.now().toString());


    String path = "src/Report/ReportStrukPembayaran.jrxml";


    report.ReportUtil.showReport(path, params);       // TODO add your handling code here:
    }//GEN-LAST:event_btnCetakStrukActionPerformed

    private void txtIdPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPenjualanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPenjualanActionPerformed

    private void txtIdPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPembayaranActionPerformed

    private void txtJumlahBayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahBayarKeyReleased
      try {
        double total = Double.parseDouble(txtTotal.getText());
        double bayar = Double.parseDouble(txtJumlahBayar.getText());
        double kembali = bayar - total;

        txtKembalian.setText(String.valueOf(kembali));
    } catch (Exception e) {
        txtKembalian.setText("0");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahBayarKeyReleased

    private void txtKembalianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKembalianKeyReleased
            // TODO add your handling code here:
    }//GEN-LAST:event_txtKembalianKeyReleased

    /**
     * @param args the command line arguments
     */

    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCetakStruk;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbMetodePembayaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblIDKategori;
    private javax.swing.JLabel lblIDKategori1;
    private javax.swing.JLabel lblIDKategori10;
    private javax.swing.JLabel lblIDKategori11;
    private javax.swing.JLabel lblIDKategori2;
    private javax.swing.JLabel lblIDKategori3;
    private javax.swing.JLabel lblIDKategori4;
    private javax.swing.JLabel lblIDKategori5;
    private javax.swing.JLabel lblIDKategori6;
    private javax.swing.JLabel lblIDKategori7;
    private javax.swing.JLabel lblIDKategori8;
    private javax.swing.JLabel lblIDKategori9;
    private javax.swing.JLabel lblNamaKategori;
    private javax.swing.JLabel lblNamaKategori1;
    private javax.swing.JTextField txtIdPembayaran;
    private javax.swing.JTextField txtIdPenjualan;
    private javax.swing.JTextField txtJumlahBayar;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void generateIdPembayaran() {
    try (Connection conn = DBConnection.getConnection()) {
        String id = IdGenerator.generateId(conn, "pembayaran", "id_pembayaran", "BY");
        txtIdPembayaran.setText(id);
    } catch (Exception e) {
        e.printStackTrace();
    }
}




   private void loadMetodePembayaran() {
    try {
        JenisPembayaranService service = new JenisPembayaranService();
        List<JenisPembayaran> list = service.getAll();

        cmbMetodePembayaran.removeAllItems();

        for (JenisPembayaran jp : list) {
          cmbMetodePembayaran.addItem(jp.getNamaJenis() + " - " + jp.getIdJenis());


        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal memuat metode pembayaran!");
    }
}

private String getSelectedJenis() {
    String item = cmbMetodePembayaran.getSelectedItem().toString();
    return item.split(" - ")[1];
}



   private void updateStatusPenjualanLunas() {
    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(
            "UPDATE penjualan SET status_pembayaran='LUNAS' WHERE id_penjualan=?"
         )) {

        ps.setString(1, txtIdPenjualan.getText());
        ps.executeUpdate();

    } catch (Exception e) {
        e.printStackTrace();
    }
}
   



}
