/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Dialog;

import javax.swing.JOptionPane;
import model.Supplier;
import service.SupplierService;


/**
 *
 * @author ryo not rio
 */

public class DialogSupplier extends javax.swing.JDialog {
 private Supplier result;   // ini yang bakal dikirim balik ke dashboard
    private boolean isUpdate = false;

    public DialogSupplier(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Creates new form DialogSupplier
     */
    
    
    
    // MODE INSERT
    public void setInsertMode() {
        isUpdate = false;

        txtIDSupplier.setEditable(true);
        txtIDSupplier.setText("");

        txtNamaSupplier.setText("");
        txtKontakSupplier.setText("");
        txtAlamatSupplier.setText("");

        btnSaveSupplier.setText("SAVE");
    }
      
     // MODE UPDATE
    public void setUpdateMode(Supplier s) {
        isUpdate = true;

        txtIDSupplier.setText(s.getIdSupplier());
        txtIDSupplier.setEditable(false);

        txtNamaSupplier.setText(s.getNamaSupplier());
        txtKontakSupplier.setText(s.getKontak());
        txtAlamatSupplier.setText(s.getAlamat());

        btnSaveSupplier.setText("UPDATE");

        result = s; // supaya pas update result sudah berisi data lama
    }
      
     
 public Supplier getResult() {
        return result;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jJudul2 = new javax.swing.JLabel();
        txtIDSupplier = new javax.swing.JTextField();
        btnSaveSupplier = new javax.swing.JButton();
        btnCancelSupplier = new javax.swing.JButton();
        lblIDKategori = new javax.swing.JLabel();
        lblNamaKategori = new javax.swing.JLabel();
        txtNamaSupplier = new javax.swing.JTextField();
        jJudul1 = new javax.swing.JLabel();
        jJudul3 = new javax.swing.JLabel();
        txtKontakSupplier = new javax.swing.JTextField();
        lblIDKategori1 = new javax.swing.JLabel();
        lblNamaKategori1 = new javax.swing.JLabel();
        txtAlamatSupplier = new javax.swing.JTextField();
        jJudul5 = new javax.swing.JLabel();
        jJudul4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SUPPLIER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 36, -1, -1));

        jJudul2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul2.setText(":");
        getContentPane().add(jJudul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 132, -1, 28));

        txtIDSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDSupplierActionPerformed(evt);
            }
        });
        getContentPane().add(txtIDSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 130, 350, 39));

        btnSaveSupplier.setBackground(new java.awt.Color(0, 0, 102));
        btnSaveSupplier.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSaveSupplier.setForeground(new java.awt.Color(204, 255, 255));
        btnSaveSupplier.setText("SAVE");
        btnSaveSupplier.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));
        btnSaveSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSupplierActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaveSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 98, 36));

        btnCancelSupplier.setBackground(new java.awt.Color(153, 0, 0));
        btnCancelSupplier.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancelSupplier.setForeground(new java.awt.Color(204, 255, 255));
        btnCancelSupplier.setText("CANCEL");
        btnCancelSupplier.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 51, 51)));
        btnCancelSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelSupplierActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 98, 36));

        lblIDKategori.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori.setText("ID Supplier");
        getContentPane().add(lblIDKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 134, 117, -1));

        lblNamaKategori.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamaKategori.setText("Nama Supplier");
        getContentPane().add(lblNamaKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 189, -1, 28));

        txtNamaSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaSupplierActionPerformed(evt);
            }
        });
        getContentPane().add(txtNamaSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 187, 348, 38));

        jJudul1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul1.setText(":");
        getContentPane().add(jJudul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 189, -1, 28));

        jJudul3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul3.setText(":");
        getContentPane().add(jJudul3, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 245, -1, 28));

        txtKontakSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKontakSupplierActionPerformed(evt);
            }
        });
        getContentPane().add(txtKontakSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 243, 350, 39));

        lblIDKategori1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIDKategori1.setText("Kontak");
        getContentPane().add(lblIDKategori1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 247, 117, -1));

        lblNamaKategori1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamaKategori1.setText("Alamat");
        getContentPane().add(lblNamaKategori1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 302, -1, 28));

        txtAlamatSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatSupplierActionPerformed(evt);
            }
        });
        getContentPane().add(txtAlamatSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 300, 348, 38));

        jJudul5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul5.setText(":");
        getContentPane().add(jJudul5, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 245, -1, 28));

        jJudul4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jJudul4.setText(":");
        getContentPane().add(jJudul4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 10, 28));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DialogBG.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDSupplierActionPerformed

    private void btnSaveSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSupplierActionPerformed
         String id = txtIDSupplier.getText().trim();
    String nama = txtNamaSupplier.getText().trim();
    String kontak = txtKontakSupplier.getText().trim();
    String alamat = txtAlamatSupplier.getText().trim();

    SupplierService service = new SupplierService();

    // VALIDASI WAJIB
    if (id.isEmpty() || nama.isEmpty() || kontak.isEmpty() || alamat.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
        return; // form tetap stay
    }

    // VALIDASI PK DUPLIKAT (hanya insert)
    if (!isUpdate) {
        if (service.existsById(id)) {
            JOptionPane.showMessageDialog(
                this, 
                "ID Supplier sudah digunakan! Masukkan ID lain."
            );
            return; // FORM TETAP STAY
        }
    }

    boolean success = false;

    try {
        if (!isUpdate) {
            // INSERT MODE
            result = new Supplier(id, nama, kontak, alamat);

        } else {
            // UPDATE MODE
            result.setNamaSupplier(nama);
            result.setKontak(kontak);
            result.setAlamat(alamat);
        }

        success = true;

    } catch (Exception e) {
        JOptionPane.showMessageDialog(
            this,
            "Terjadi kesalahan saat menyimpan supplier: " + e.getMessage()
        );
    }

    // FORM HANYA TUTUP KALO SUKSES
    if (success) {
        dispose();
    }
    }//GEN-LAST:event_btnSaveSupplierActionPerformed

    private void btnCancelSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelSupplierActionPerformed
         result = null;
        dispose();
    }//GEN-LAST:event_btnCancelSupplierActionPerformed

    private void txtNamaSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaSupplierActionPerformed

    private void txtKontakSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKontakSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKontakSupplierActionPerformed

    private void txtAlamatSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatSupplierActionPerformed

    /**
     * @param args the command line arguments
     */


 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelSupplier;
    private javax.swing.JButton btnSaveSupplier;
    private javax.swing.JLabel jJudul1;
    private javax.swing.JLabel jJudul2;
    private javax.swing.JLabel jJudul3;
    private javax.swing.JLabel jJudul4;
    private javax.swing.JLabel jJudul5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblIDKategori;
    private javax.swing.JLabel lblIDKategori1;
    private javax.swing.JLabel lblNamaKategori;
    private javax.swing.JLabel lblNamaKategori1;
    private javax.swing.JTextField txtAlamatSupplier;
    private javax.swing.JTextField txtIDSupplier;
    private javax.swing.JTextField txtKontakSupplier;
    private javax.swing.JTextField txtNamaSupplier;
    // End of variables declaration//GEN-END:variables




    



}
