/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import service.PegawaiService;
import util.DBConnection;
import util.Session;


/**
 *
 * @author ryo not rio
 */
public class ForgotPasswordFrame extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPasswordFrame
     */
public ForgotPasswordFrame() {
    initComponents();
         this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    panelResetPassword.setVisible(false);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        panelResetPassword = new javax.swing.JPanel();
        lblPass2 = new javax.swing.JLabel();
        txtPass2 = new javax.swing.JPasswordField();
        lblPass1 = new javax.swing.JLabel();
        txtPass1 = new javax.swing.JPasswordField();
        btnSimpanPassword = new javax.swing.JButton();
        cbShowPassword = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblInstruction1 = new javax.swing.JLabel();
        btnKirimOTP = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BACK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMain.setBackground(new java.awt.Color(204, 51, 255));
        panelMain.setPreferredSize(new java.awt.Dimension(1900, 1080));
        panelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 204, 102));
        lblTitle.setText("LUPA PASSWORD");
        panelMain.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 460, -1));

        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(0, 0, 102)));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        panelMain.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 450, 40));

        panelResetPassword.setBackground(new java.awt.Color(204, 51, 255));
        panelResetPassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPass2.setBackground(new java.awt.Color(255, 255, 255));
        lblPass2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPass2.setForeground(new java.awt.Color(255, 255, 255));
        lblPass2.setText("Konfirmasi Password :");
        panelResetPassword.add(lblPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        txtPass2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(0, 0, 102)));
        txtPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPass2ActionPerformed(evt);
            }
        });
        panelResetPassword.add(txtPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 450, 40));

        lblPass1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPass1.setForeground(new java.awt.Color(255, 255, 255));
        lblPass1.setText("Password Baru :");
        panelResetPassword.add(lblPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        txtPass1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(0, 0, 102)));
        txtPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPass1ActionPerformed(evt);
            }
        });
        panelResetPassword.add(txtPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 450, 40));

        btnSimpanPassword.setBackground(new java.awt.Color(0, 153, 0));
        btnSimpanPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSimpanPassword.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpanPassword.setText("SIMPAN PASSWORD");
        btnSimpanPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 255, 0)));
        btnSimpanPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpanPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanPasswordActionPerformed(evt);
            }
        });
        panelResetPassword.add(btnSimpanPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 450, 40));

        cbShowPassword.setBackground(new java.awt.Color(204, 51, 255));
        cbShowPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        cbShowPassword.setText("Show password");
        cbShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowPasswordActionPerformed(evt);
            }
        });
        panelResetPassword.add(cbShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logonyk.png"))); // NOI18N
        panelResetPassword.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, -190, 1630, 600));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logonyk.png"))); // NOI18N
        panelResetPassword.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, -230, 1630, 600));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logonyk.png"))); // NOI18N
        panelResetPassword.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 1630, 600));

        panelMain.add(panelResetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 680, 320));

        lblInstruction1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblInstruction1.setForeground(new java.awt.Color(255, 255, 255));
        lblInstruction1.setText("Masukkan Email/Username :");
        panelMain.add(lblInstruction1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 290, -1));

        btnKirimOTP.setBackground(new java.awt.Color(0, 102, 153));
        btnKirimOTP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnKirimOTP.setForeground(new java.awt.Color(255, 255, 255));
        btnKirimOTP.setText("Kirim Kode OTP");
        btnKirimOTP.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 255, 255)));
        btnKirimOTP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKirimOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKirimOTPActionPerformed(evt);
            }
        });
        panelMain.add(btnKirimOTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 450, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logonyk.png"))); // NOI18N
        panelMain.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 1630, 600));

        BACK.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        BACK.setForeground(new java.awt.Color(255, 0, 0));
        BACK.setText("<");
        BACK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BACKMouseClicked(evt);
            }
        });
        panelMain.add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnKirimOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKirimOTPActionPerformed
        String username = txtEmail.getText().trim();
    PegawaiService service = new PegawaiService();

    if (username.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Tidak boleh kosong!");
        return;
    }

    if (!service.existsForForgot(username)) {
        JOptionPane.showMessageDialog(this, "Username tidak ditemukan!");
        return;
    }

    // Simpan session
    Session.currentUsername = username;

    // generate OTP
    int otp = (int)(Math.random() * 900000) + 100000;
    Session.currentOTP = otp;

    String input = JOptionPane.showInputDialog(this,
            "Kode OTP kamu: " + otp + "\nMasukkan OTP:");

    if (input == null) return;

    if (!input.equals(String.valueOf(otp))) {
        JOptionPane.showMessageDialog(this, "OTP salah!");
        return;
    }

    // OTP benar → tampilkan panel reset
    panelResetPassword.setVisible(true);
    JOptionPane.showMessageDialog(this, "OTP benar! Silakan ganti password.");
    }//GEN-LAST:event_btnKirimOTPActionPerformed

    private void BACKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseClicked
     new LoginFrame().setVisible(true);
     this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_BACKMouseClicked

    private void txtPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPass2ActionPerformed

    private void txtPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPass1ActionPerformed

    private void btnSimpanPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPasswordActionPerformed
    String pass1 = new String(txtPass1.getPassword());
    String pass2 = new String(txtPass2.getPassword());

    if (pass1.isEmpty() || pass2.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Password tidak boleh kosong!");
        return;
    }

    if (!pass1.equals(pass2)) {
        JOptionPane.showMessageDialog(this, "Password tidak sama!");
        return;
    }

    try {
    Connection conn = (Connection) DBConnection.getConnection();
    String sql = "UPDATE pegawai SET password = ? WHERE username = ?";
    PreparedStatement pst = conn.prepareStatement(sql);

    pst.setString(1, pass1);
    pst.setString(2, Session.currentUsername);

    int rows = pst.executeUpdate();

    if (rows > 0) {
        JOptionPane.showMessageDialog(this, "Password berhasil diperbarui!");
        Session.clear();
        new LoginFrame().setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Gagal memperbarui password!");
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}

    
// TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanPasswordActionPerformed

    private void cbShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPasswordActionPerformed
    if (cbShowPassword.isSelected()) {
        txtPass1.setEchoChar((char)0);
        txtPass2.setEchoChar((char)0);
    } else {
        txtPass1.setEchoChar('•');
        txtPass2.setEchoChar('•');
    }          // TODO add your handling code here:
    }//GEN-LAST:event_cbShowPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
   
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACK;
    private javax.swing.JButton btnKirimOTP;
    private javax.swing.JButton btnSimpanPassword;
    private javax.swing.JCheckBox cbShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblInstruction1;
    private javax.swing.JLabel lblPass1;
    private javax.swing.JLabel lblPass2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelResetPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPass1;
    private javax.swing.JPasswordField txtPass2;
    // End of variables declaration//GEN-END:variables
}
