/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Pegawai;
import service.PegawaiService;

/**
 *
 * @author ryo not rio
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
   public LoginFrame() {
    initComponents();
     this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    cbRole.addItem("Admin");
    cbRole.addItem("Kasir");
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelMain = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblLoginAs = new javax.swing.JLabel();
        lblSignUp = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblForgotPassword = new javax.swing.JLabel();
        lblNoAccount = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        cbShowPassword = new javax.swing.JCheckBox();
        cbRole = new javax.swing.JComboBox<>();
        lblPassword = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMain.setBackground(new java.awt.Color(0, 0, 102));
        panelMain.setPreferredSize(new java.awt.Dimension(1920, 1080));
        panelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 204, 0));
        lblTitle.setText("LOGIN PAGE");
        panelMain.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        lblLoginAs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLoginAs.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginAs.setText("Login Sebagai :");
        panelMain.add(lblLoginAs, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));

        lblSignUp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSignUp.setForeground(new java.awt.Color(255, 255, 255));
        lblSignUp.setText("Sign up");
        lblSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSignUpMouseClicked(evt);
            }
        });
        panelMain.add(lblSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 660, -1, -1));

        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 5, 1, new java.awt.Color(0, 0, 102)));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        panelMain.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 480, 40));

        lblUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username :");
        panelMain.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        btnLogin.setBackground(new java.awt.Color(0, 102, 51));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOG IN");
        btnLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(102, 255, 0)));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        panelMain.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 480, 40));

        lblForgotPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblForgotPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblForgotPassword.setText("Forgot password?");
        lblForgotPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblForgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblForgotPasswordMouseClicked(evt);
            }
        });
        panelMain.add(lblForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, -1, -1));

        lblNoAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNoAccount.setForeground(new java.awt.Color(255, 255, 255));
        lblNoAccount.setText("Don't have an account ?");
        panelMain.add(lblNoAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 660, -1, -1));

        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 5, 1, new java.awt.Color(0, 0, 102)));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        panelMain.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 480, 40));

        cbShowPassword.setBackground(new java.awt.Color(153, 51, 255));
        cbShowPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        cbShowPassword.setText("Show password");
        cbShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowPasswordActionPerformed(evt);
            }
        });
        panelMain.add(cbShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, -1, -1));

        cbRole.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 5, 1, new java.awt.Color(0, 0, 102)));
        cbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRoleActionPerformed(evt);
            }
        });
        panelMain.add(cbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 480, 40));

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password :");
        panelMain.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logonyk.png"))); // NOI18N
        panelMain.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 1630, 600));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logooobg.png"))); // NOI18N
        panelMain.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -30, 3960, 1170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignUpMouseClicked
        new RegisterFrame().setVisible(true);
     this.dispose();  
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSignUpMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
      String username = txtUsername.getText().trim();
    String password = new String(txtPassword.getPassword());
    String role = cbRole.getSelectedItem().toString(); // Admin / Kasir

    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username dan password wajib diisi!");
        return;
    }

    PegawaiService service = new PegawaiService();
    Pegawai p = service.login(username, password, role);

    if (p == null) {
        JOptionPane.showMessageDialog(this, "Username / Password / Role salah!");
        return;
    }

    JOptionPane.showMessageDialog(this, "Login sukses, " + p.getNama());

    if (role.equalsIgnoreCase("Admin")) {
        new AdminDashboard(p.getId(), p.getNama()).setVisible(true);


} else {
    new KasirDashboard(p.getId(), p.getNama()).setVisible(true);
}

    this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblForgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotPasswordMouseClicked
    new ui.ForgotPasswordFrame().setVisible(true);
    this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_lblForgotPasswordMouseClicked

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void cbShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPasswordActionPerformed
        if (cbShowPassword.isSelected()) {
            txtPassword.setEchoChar((char) 0);  // password kelihatan
        } else {
            txtPassword.setEchoChar('•'); // atau default: (char)8226
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cbShowPasswordActionPerformed

    private void cbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRoleActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRoleActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JCheckBox cbShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblForgotPassword;
    private javax.swing.JLabel lblLoginAs;
    private javax.swing.JLabel lblNoAccount;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSignUp;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
