/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Pegawai;
import service.PegawaiService;

/**
 *
 * @author ryo not rio
 */
public class RegisterFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterFrame
     */
public RegisterFrame() {
 initComponents();     this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    cbRole.addItem("Admin");
    cbRole.addItem("Kasir");
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblLoginAs = new javax.swing.JLabel();
        lblGotoLogin = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        btnDaftar = new javax.swing.JButton();
        lblNoAccount = new javax.swing.JLabel();
        cbShowPassword = new javax.swing.JCheckBox();
        cbRole = new javax.swing.JComboBox<>();
        lblUsername = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblPassword1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMain.setBackground(new java.awt.Color(51, 0, 153));
        panelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 204, 102));
        lblTitle.setText("BUAT AKUN BARU");
        panelMain.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 500, -1));

        lblLoginAs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLoginAs.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginAs.setText("Daftar Sebagai :");
        panelMain.add(lblLoginAs, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 180, -1));

        lblGotoLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGotoLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblGotoLogin.setText("Login di sini");
        lblGotoLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGotoLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGotoLoginMouseClicked(evt);
            }
        });
        panelMain.add(lblGotoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 690, 130, -1));

        lblNama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNama.setForeground(new java.awt.Color(255, 255, 255));
        lblNama.setText("Nama Lengkap :");
        panelMain.add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 180, -1));

        btnDaftar.setBackground(new java.awt.Color(0, 102, 51));
        btnDaftar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDaftar.setForeground(new java.awt.Color(255, 255, 255));
        btnDaftar.setText("DAFTAR SEKARANG");
        btnDaftar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(102, 255, 0)));
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });
        panelMain.add(btnDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 640, 440, 40));

        lblNoAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNoAccount.setForeground(new java.awt.Color(255, 255, 255));
        lblNoAccount.setText("Sudah punya akun ?");
        panelMain.add(lblNoAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 690, 180, -1));

        cbShowPassword.setBackground(new java.awt.Color(153, 51, 255));
        cbShowPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        cbShowPassword.setText("Show password");
        cbShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowPasswordActionPerformed(evt);
            }
        });
        panelMain.add(cbShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 170, -1));

        cbRole.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 5, 1, new java.awt.Color(0, 0, 102)));
        cbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRoleActionPerformed(evt);
            }
        });
        panelMain.add(cbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 440, 40));

        lblUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username :");
        panelMain.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 140, -1));

        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 5, 1, new java.awt.Color(0, 0, 102)));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        panelMain.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 440, 40));

        lblPassword1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPassword1.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword1.setText("Password :");
        panelMain.add(lblPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 140, -1));

        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 5, 1, new java.awt.Color(0, 0, 102)));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        panelMain.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 440, 40));

        txtNama.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 5, 1, new java.awt.Color(0, 0, 102)));
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        panelMain.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 440, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logonyk.png"))); // NOI18N
        panelMain.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 1630, 600));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logooobg.png"))); // NOI18N
        panelMain.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 910));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblGotoLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGotoLoginMouseClicked
     new LoginFrame().setVisible(true);
    this.dispose(); 
        // TODO add your handling code here:
    }//GEN-LAST:event_lblGotoLoginMouseClicked

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
     Pegawai p = new Pegawai();

    p.setNama(txtNama.getText());
    p.setUsername(txtEmail.getText());
    p.setPassword(txtPassword.getText());
    p.setJabatan(cbRole.getSelectedItem().toString());

    PegawaiService service = new PegawaiService();

    if (service.isUsernameExist(p.getUsername())) {
        JOptionPane.showMessageDialog(this, "Username sudah digunakan!");
        return;
    }

    boolean ok = service.register(p);

    if (ok) {
        JOptionPane.showMessageDialog(this, "Registrasi berhasil!");
        this.dispose();
        new LoginFrame().setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Registrasi gagal!");
    }
    }//GEN-LAST:event_btnDaftarActionPerformed

    private void cbShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPasswordActionPerformed
         if (cbShowPassword.isSelected()) {
            txtPassword.setEchoChar((char) 0);  // password kelihatan
        } else {
            txtPassword.setEchoChar('•'); // atau default: (char)8226
        }         // TODO add your handling code here:
    }//GEN-LAST:event_cbShowPasswordActionPerformed

    private void cbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRoleActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_cbRoleActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaftar;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JCheckBox cbShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblGotoLogin;
    private javax.swing.JLabel lblLoginAs;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNoAccount;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel panelMain;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNama;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
//blom