-- ================================
-- MASTER TABEL
-- ================================

CREATE TABLE KATEGORI (
    ID_KATEGORI   VARCHAR(5)  NOT NULL,
    NAMA_KATEGORI VARCHAR(50) NOT NULL,
    CONSTRAINT PK_KATEGORI PRIMARY KEY (ID_KATEGORI)
);

CREATE TABLE SUPPLIER (
    ID_SUPPLIER   VARCHAR(5)  NOT NULL,
    NAMA_SUPPLIER VARCHAR(50) NOT NULL,
    KONTAK        VARCHAR(12) NOT NULL,
    ALAMAT        VARCHAR(50) NOT NULL,
    CONSTRAINT PK_SUPPLIER PRIMARY KEY (ID_SUPPLIER)
);

CREATE TABLE PEMBELI (
    ID_PEMBELI   VARCHAR(5)  NOT NULL,
    NAMA_PEMBELI VARCHAR(50) NOT NULL,
    NO_TELEPON   VARCHAR(15) NOT NULL,
    ALAMAT       VARCHAR(50) NOT NULL,
    CONSTRAINT PK_PEMBELI PRIMARY KEY (ID_PEMBELI)
);

CREATE TABLE PEGAWAI (
    ID_PEGAWAI    VARCHAR(5)  NOT NULL,
    NAMA_PEGAWAI  VARCHAR(50) NOT NULL,
    JABATAN       VARCHAR(25) NOT NULL,      -- 'ADMIN' / 'KASIR'
    USERNAME      VARCHAR(30) NOT NULL UNIQUE,
    PASSWORD      VARCHAR(255) NOT NULL,
    CONSTRAINT PK_PEGAWAI PRIMARY KEY (ID_PEGAWAI)
);

CREATE TABLE JENIS_PEMBAYARAN (
    ID_JENIS    VARCHAR(5)   NOT NULL,
    NAMA_JENIS  VARCHAR(25)  NOT NULL,
    KETERANGAN  VARCHAR(100),
    CONSTRAINT PK_JENIS_PEMBAYARAN PRIMARY KEY (ID_JENIS)
);

-- ================================
-- BARANG & KATEGORI
-- ================================

CREATE TABLE BARANG (
    ID_BARANG   VARCHAR(5)    NOT NULL,
    ID_KATEGORI VARCHAR(5),
    NAMA_BARANG VARCHAR(50)   NOT NULL,
    HARGA       DECIMAL(12,2) NOT NULL,
    STOCK       INT4          NOT NULL,
    CONSTRAINT PK_BARANG PRIMARY KEY (ID_BARANG)
);

CREATE INDEX IDX_BARANG_KATEGORI ON BARANG (ID_KATEGORI);

-- ================================
-- PENJUALAN
-- ================================

CREATE TABLE PENJUALAN (
    ID_PENJUALAN      VARCHAR(5)    NOT NULL,
    ID_PEGAWAI        VARCHAR(5)    NOT NULL,
    ID_PEMBELI        VARCHAR(5),
    TANGGAL           DATE          NOT NULL,
    TOTAL             DECIMAL(12,2) NOT NULL,
    STATUS_PEMBAYARAN VARCHAR(25)   NOT NULL,
    CONSTRAINT PK_PENJUALAN PRIMARY KEY (ID_PENJUALAN)
);

CREATE INDEX IDX_PENJUALAN_PEGAWAI ON PENJUALAN (ID_PEGAWAI);
CREATE INDEX IDX_PENJUALAN_PEMBELI ON PENJUALAN (ID_PEMBELI);

-- ================================
-- PEMBAYARAN
-- ================================

CREATE TABLE PEMBAYARAN (
    ID_PEMBAYARAN      VARCHAR(5)    NOT NULL,
    ID_PENJUALAN       VARCHAR(5)    NOT NULL,
    ID_JENIS           VARCHAR(5)    NOT NULL,
    TANGGAL_PEMBAYARAN DATE          NOT NULL,
    JUMLAH_BAYAR       DECIMAL(12,2) NOT NULL,
    CONSTRAINT PK_PEMBAYARAN PRIMARY KEY (ID_PEMBAYARAN)
);

CREATE INDEX IDX_PEMBAYARAN_PENJUALAN ON PEMBAYARAN (ID_PENJUALAN);
CREATE INDEX IDX_PEMBAYARAN_JENIS      ON PEMBAYARAN (ID_JENIS);

-- ================================
-- RESTOCK
-- ================================

CREATE TABLE RESTOCK (
    ID_RESTOCK  VARCHAR(5) NOT NULL,
    ID_PEGAWAI  VARCHAR(5) NOT NULL,
    ID_SUPPLIER VARCHAR(5) NOT NULL,
    TANGGAL     DATE       NOT NULL,
    JUMLAH      INT4       NOT NULL,
    CONSTRAINT PK_RESTOCK PRIMARY KEY (ID_RESTOCK)
);

CREATE INDEX IDX_RESTOCK_PEGAWAI  ON RESTOCK (ID_PEGAWAI);
CREATE INDEX IDX_RESTOCK_SUPPLIER ON RESTOCK (ID_SUPPLIER);

-- ================================
-- DETAIL TRANSAKSI
-- ================================

CREATE TABLE DETAIL_PENJUALAN (
    ID_DETAIL_PENJUALAN VARCHAR(5)    NOT NULL,
    ID_PENJUALAN        VARCHAR(5)    NOT NULL,
    ID_BARANG           VARCHAR(5)    NOT NULL,
    JUMLAH              INT4          NOT NULL,
    SUBTOTAL            DECIMAL(12,2) NOT NULL,
    CONSTRAINT PK_DETAIL_PENJUALAN PRIMARY KEY (ID_DETAIL_PENJUALAN)
);

CREATE UNIQUE INDEX UQ_DETAIL_PENJUALAN_PENJUALAN_BARANG
    ON DETAIL_PENJUALAN (ID_PENJUALAN, ID_BARANG);

CREATE INDEX IDX_DETAIL_PENJUALAN_PENJUALAN ON DETAIL_PENJUALAN (ID_PENJUALAN);
CREATE INDEX IDX_DETAIL_PENJUALAN_BARANG    ON DETAIL_PENJUALAN (ID_BARANG);

CREATE TABLE DETAIL_RESTOCK (
    ID_DETAIL_RESTOCK VARCHAR(5)     NOT NULL,
    ID_RESTOCK        VARCHAR(5)     NOT NULL,
    ID_BARANG         VARCHAR(5)     NOT NULL,
    JUMLAH            INT4           NOT NULL,
    HARGA_BELI        DECIMAL(12,2)  NOT NULL,
    CONSTRAINT PK_DETAIL_RESTOCK PRIMARY KEY (ID_DETAIL_RESTOCK)
);

CREATE INDEX IDX_DETAIL_RESTOCK_RESTOCK ON DETAIL_RESTOCK (ID_RESTOCK);
CREATE INDEX IDX_DETAIL_RESTOCK_BARANG  ON DETAIL_RESTOCK (ID_BARANG);

-- ================================
-- FOREIGN KEYS
-- ================================

-- BARANG ↔ KATEGORI
ALTER TABLE BARANG
    ADD CONSTRAINT FK_BARANG_KATEGORI
    FOREIGN KEY (ID_KATEGORI)
    REFERENCES KATEGORI (ID_KATEGORI)
    ON DELETE SET NULL
    ON UPDATE RESTRICT;

-- PENJUALAN ↔ PEGAWAI & PEMBELI
ALTER TABLE PENJUALAN
    ADD CONSTRAINT FK_PENJUALAN_PEGAWAI
    FOREIGN KEY (ID_PEGAWAI)
    REFERENCES PEGAWAI (ID_PEGAWAI)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE PENJUALAN
    ADD CONSTRAINT FK_PENJUALAN_PEMBELI
    FOREIGN KEY (ID_PEMBELI)
    REFERENCES PEMBELI (ID_PEMBELI)
    ON DELETE SET NULL
    ON UPDATE RESTRICT;

-- PEMBAYARAN ↔ PENJUALAN & JENIS_PEMBAYARAN
ALTER TABLE PEMBAYARAN
    ADD CONSTRAINT FK_PEMBAYARAN_PENJUALAN
    FOREIGN KEY (ID_PENJUALAN)
    REFERENCES PENJUALAN (ID_PENJUALAN)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE PEMBAYARAN
    ADD CONSTRAINT FK_PEMBAYARAN_JENIS
    FOREIGN KEY (ID_JENIS)
    REFERENCES JENIS_PEMBAYARAN (ID_JENIS)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

-- RESTOCK ↔ PEGAWAI & SUPPLIER
ALTER TABLE RESTOCK
    ADD CONSTRAINT FK_RESTOCK_PEGAWAI
    FOREIGN KEY (ID_PEGAWAI)
    REFERENCES PEGAWAI (ID_PEGAWAI)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE RESTOCK
    ADD CONSTRAINT FK_RESTOCK_SUPPLIER
    FOREIGN KEY (ID_SUPPLIER)
    REFERENCES SUPPLIER (ID_SUPPLIER)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

-- DETAIL_PENJUALAN ↔ PENJUALAN & BARANG
ALTER TABLE DETAIL_PENJUALAN
    ADD CONSTRAINT FK_DETAIL_PENJUALAN_PENJUALAN
    FOREIGN KEY (ID_PENJUALAN)
    REFERENCES PENJUALAN (ID_PENJUALAN)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE DETAIL_PENJUALAN
    ADD CONSTRAINT FK_DETAIL_PENJUALAN_BARANG
    FOREIGN KEY (ID_BARANG)
    REFERENCES BARANG (ID_BARANG)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

-- DETAIL_RESTOCK ↔ RESTOCK & BARANG
ALTER TABLE DETAIL_RESTOCK
    ADD CONSTRAINT FK_DETAIL_RESTOCK_RESTOCK
    FOREIGN KEY (ID_RESTOCK)
    REFERENCES RESTOCK (ID_RESTOCK)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE DETAIL_RESTOCK
    ADD CONSTRAINT FK_DETAIL_RESTOCK_BARANG
    FOREIGN KEY (ID_BARANG)
    REFERENCES BARANG (ID_BARANG)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;


	=================



